# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 358)
        self.btnCalculate = QtWidgets.QPushButton(Dialog)
        self.btnCalculate.setGeometry(QtCore.QRect(30, 250, 101, 81))
        self.btnCalculate.setObjectName("btnCalculate")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 291, 211))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label_7.setObjectName("label_7")
        self.tbWidth = QtWidgets.QLineEdit(self.groupBox)
        self.tbWidth.setGeometry(QtCore.QRect(192, 20, 81, 22))
        self.tbWidth.setObjectName("tbWidth")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 111, 16))
        self.label_2.setObjectName("label_2")
        self.tbHeight = QtWidgets.QLineEdit(self.groupBox)
        self.tbHeight.setGeometry(QtCore.QRect(192, 50, 81, 22))
        self.tbHeight.setObjectName("tbHeight")
        self.btnAddWall = QtWidgets.QPushButton(self.groupBox)
        self.btnAddWall.setGeometry(QtCore.QRect(10, 80, 261, 28))
        self.btnAddWall.setObjectName("btnAddWall")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 110, 151, 41))
        self.label_8.setObjectName("label_8")
        self.tbTotalSurface = QtWidgets.QLineEdit(self.groupBox)
        self.tbTotalSurface.setEnabled(False)
        self.tbTotalSurface.setGeometry(QtCore.QRect(190, 120, 81, 22))
        self.tbTotalSurface.setObjectName("tbTotalSurface")
        self.btnResetRoom = QtWidgets.QPushButton(self.groupBox)
        self.btnResetRoom.setGeometry(QtCore.QRect(170, 160, 101, 28))
        self.btnResetRoom.setObjectName("btnResetRoom")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 50, 231, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 211, 16))
        self.label_3.setObjectName("label_3")
        self.tbEfficiency = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbEfficiency.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.tbEfficiency.setObjectName("tbEfficiency")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 80, 231, 20))
        self.label.setObjectName("label")
        self.tbMinExcess = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbMinExcess.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.tbMinExcess.setObjectName("tbMinExcess")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 240, 391, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 131, 31))
        self.label_5.setObjectName("label_5")
        self.lblResult = QtWidgets.QLabel(self.groupBox_3)
        self.lblResult.setGeometry(QtCore.QRect(190, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.lblExcessResult = QtWidgets.QLabel(self.groupBox_3)
        self.lblExcessResult.setGeometry(QtCore.QRect(190, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblExcessResult.setFont(font)
        self.lblExcessResult.setObjectName("lblExcessResult")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(300, 20, 81, 31))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnCalculate.setText(_translate("Dialog", "Calculate"))
        self.groupBox.setTitle(_translate("Dialog", "Room creator"))
        self.label_7.setText(_translate("Dialog", "Wall width [m]"))
        self.label_2.setText(_translate("Dialog", "Wall height [m]"))
        self.btnAddWall.setText(_translate("Dialog", "Add wall"))
        self.label_8.setText(_translate("Dialog", "Total room surface [m^2]"))
        self.btnResetRoom.setText(_translate("Dialog", "Reset room"))
        self.groupBox_2.setTitle(_translate("Dialog", "Calculator configuration"))
        self.label_3.setText(_translate("Dialog", "Paint can efficiency [ m^2 / can ]"))
        self.label.setText(_translate("Dialog", "Minimum excess (f.i. 0.23 for 23%)"))
        self.groupBox_3.setTitle(_translate("Dialog", "Results"))
        self.label_4.setText(_translate("Dialog", "You need to buy: "))
        self.label_5.setText(_translate("Dialog", "Total excess will be"))
        self.lblResult.setText(_translate("Dialog", "-"))
        self.lblExcessResult.setText(_translate("Dialog", "-"))
        self.label_6.setText(_translate("Dialog", "paint cans."))

